=== brossetti1/hashmasks-db/collections.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1613598235.json",
  "title": "Root",
  "type": "array",
  "default": [],
  "items": {
    "$id": "#root/items",
    "title": "Items",
    "type": "object",
    "required": ["id", "fullName", "category", "children"],
    "properties": {
      "id": {
        "$id": "#root/items/id",
        "title": "Id",
        "type": "string",
        "default": "",
        "examples": ["planets"],
        "pattern": "^.*$"
      },
      "fullName": {
        "$id": "#root/items/fullName",
        "title": "Fullname",
        "type": "string",
        "default": "",
        "examples": ["Planet Signs"],
        "pattern": "^.*$"
      },
      "category": {
        "$id": "#root/items/category",
        "title": "Category",
        "type": "string",
        "default": "",
        "examples": ["backgrounds"],
        "pattern": "^.*$"
      },
      "children": {
        "$id": "#root/items/children",
        "title": "Children",
        "type": "array",
        "default": [],
        "items": {
          "$id": "#root/items/children/items",
          "title": "Items",
          "type": "object",
          "required": ["id", "fullName", "maskIds"],
          "properties": {
            "id": {
              "$id": "#root/items/children/items/id",
              "title": "Id",
              "type": "string",
              "default": "",
              "examples": ["ceres"],
              "pattern": "^.*$"
            },
            "fullName": {
              "$id": "#root/items/children/items/fullName",
              "title": "Fullname",
              "type": "string",
              "default": "",
              "examples": ["Ceres"],
              "pattern": "^.*$"
            },
            "maskIds": {
              "$id": "#root/items/children/items/maskIds",
              "title": "Maskids",
              "type": "array",
              "default": [],
              "items": {
                "$id": "#root/items/children/items/maskIds/items",
                "title": "Items",
                "type": "integer",
                "examples": [10239],
                "default": 0
              }
            }
          }
        }
      }
    }
  }
}

=== brossetti1/hashmasks-db/collections.json
[
  {
    "id": "planets",
    "fullName": "Planet Signs",
    "category": "backgrounds",
    "children": [
      {
        "id": "ceres",
        "fullName": "Ceres",
        "maskIds": [
          10239,
          10533,
          10814,
          10854,
          10882,
          11423,
          13122,
          13180,
          13237,
          13285,
          13484,
          13794,
          1381,
          14723,
          15487,
          15656,
          1601,
          16280,
          16327,
          1799,
          2107,
          2508,
          2620,
          2849,
          3437,
          3837,
          3857,
          4322,
          5245,
          5477,
          5930,
          6271,
          7157,
          7399,
          7501,
          7816,
          790,
          9212,
          9338,
          9597,
          9695
        ]
      },
      {
        "id": "chiron",
        "fullName": "Chiron",
        "maskIds": []
      }
    ]
  },
  {
    "id": "greek",
    "fullName": "Greek Letters",
    "category": "backgrounds",
    "children": []
  },
  {
    "id": "egyptian",
    "fullName": "Egyptian Hieroglyphs",
    "category": "backgrounds",
    "children": []
  },
  {
    "id": "astrology",
    "fullName": "Astrology Glyphss",
    "category": "backgrounds",
    "children": []
  }
]
